### PR TITLE
Tweak Prompts

### PR DESCRIPTION
**Pull request by sarganar**
In order to make it more translator-friendly

### CODE REVIEW

**Comment by curiousdannii** [comment]
'Usually' doesn't actually change anything, so this commit won't have any effect. But what would be appropriate would be to change it to use the rule responses system. Would you be interested in doing that?

**Comment by sarganar** [comment]
I plan translate some elements of Attack to spanish (like messages and prompt texts), but using a third party extension: Attack ES, wihtout the need to touch original Attack.


In he case of:

    The action prompt is "Act>".
    The reaction prompt is "React>".

I tried to change them but with the wrong way (when you set the 'usually' word, you can overwrite the value with another similar assertion) . I forgotten the fact hat they are variables.

Finally I used the when play begins rule:

    When play begins:
        now The action prompt is "Acción>";
        now The reaction prompt is "Reacción>".

sorry for that. and thank for the response.

**Comment by sarganar** [comment]
Oh God, does this system not create separates pull request?

**Comment by mciul** [comment]
The pull request looks fine to me. I'll merge it.

**Pull request merged**
